services:
  postgres:
    image: postgres:16-alpine
    container_name: financas_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: financas_user
      POSTGRES_PASSWORD: financas_pass
      POSTGRES_DB: financas_casa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financas_user -d financas_casa"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
